name: flutter_esim
description: "A Flutter plugin for eSim, checker and installer. This repository hosts a Flutter plugin designed to check device compatibility with eSIM and facilitate the installation of eSIM profiles directly within a Flutter app. The plugin provides a seamless way for developers to determine if a device supports eSIM and, if so, allows them to integrate eSIM functionality into their applications."
version: 0.0.4
homepage: https://github.com/hiennguyen92/flutter_esim
repository: https://github.com/hiennguyen92/flutter_esim
issue_tracker: https://github.com/hiennguyen92/flutter_esim/issues

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.hiennv.flutter_esim
        pluginClass: FlutterEsimPlugin
